"""Export the calibrated parameter set for the Cadence/Spectre flow:
  netlists/spectre/ucm_cfet_params.scs  (parameters section, one line per device)
  cadence/ade/calibrated_design_variables.csv (ADE design variables per platform)
Run: python3 -m sim.export_cadence_params
"""
import os, json, csv
from .platforms import DEVICES, PLATFORMS, PARAM_ORDER, INF, PLATFORM_ORDER

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main():
    cal = json.load(open(os.path.join(HERE, "data", "calibrated_params.json")))
    lines = ["// ucm_cfet_params.scs -- calibrated UCM-CFET instance parameters (generated by sim/export_cadence_params.py)",
             "// include with: include \"ucm_cfet_params.scs\"  then e.g.  Mn (d g s b) gaa_n L=L_gaa_n VTH0=VTH0_gaa_n ...",
             "simulator lang=spectre"]
    for name, dev in DEVICES.items():
        p = dict(dev["params"]); p.update(cal.get(name, {}))
        lines.append(f"// {name}: {dev['material']} {dev['polarity']}-FET")
        lines.append("parameters " + " ".join(f"{k}_{name}={(1e9 if p[k] == INF else p[k])!r}" for k in PARAM_ORDER))
    open(os.path.join(HERE, "netlists", "spectre", "ucm_cfet_params.scs"), "w").write("\n".join(lines) + "\n")
    rows = []
    for pl in PLATFORM_ORDER:
        P = PLATFORMS[pl]; n, p_ = P["n"], P["p"]
        cn = dict(DEVICES[n]["params"], **cal.get(n, {})); cp = dict(DEVICES[p_]["params"], **cal.get(p_, {}))
        rows.append(dict(platform=pl, VDD=P["vdd"], TEMP=27, CLOAD=P["cload"], CSTACK=P["cstack"], COUT=P["cout"], RLOCAL=P["rlocal"],
                         RTH=cn["RTH"], CTH=cn["CTH"], Wn=cn["W"], Wp=cp["W"], Lg=cn["L"], NNSn=cn["NNS"], NNSp=cp["NNS"],
                         VTHN=cn["VTH0"], VTHP=cp["VTH0"], MUN=cn["MU0"], MUP=cp["MU0"], RCN=cn["RSW"], RCP=cp["RSW"],
                         n_device=n, p_device=p_))
    with open(os.path.join(HERE, "cadence", "ade", "calibrated_design_variables.csv"), "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys())); w.writeheader(); w.writerows(rows)
    print("wrote netlists/spectre/ucm_cfet_params.scs and cadence/ade/calibrated_design_variables.csv")


if __name__ == "__main__":
    main()
