"""Emit the nine Verilog-A compact-model modules from sim/platforms.py.

Run:  python3 -m sim.gen_veriloga   (writes veriloga/<cell>.va)
The modules are Spectre/ADE compatible (constants.vams/disciplines.vams, 4 terminals d g s b,
internal nodes di si tj, charge-conserving ddt() contributions, smooth softplus/tanh functions).
"""
from __future__ import annotations
import json, os, datetime
from .platforms import DEVICES, PARAM_ORDER, PARAM_DOC, TRANSPORT_LANDAUER, INF

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def fmt(v):
    if v == INF:
        return "1.0e9"
    return repr(float(v))


def load_calibrated():
    f = os.path.join(HERE, "data", "calibrated_params.json")
    return json.load(open(f)) if os.path.exists(f) else {}


def module_source(name: str, dev: dict, params: dict) -> str:
    sign = 1 if dev["polarity"] == "n" else -1
    plist = "\n".join(
        f"parameter real {k} = {fmt(params[k])};  // {PARAM_DOC[k]}" for k in PARAM_ORDER)
    if dev["transport"] == TRANSPORT_LANDAUER:
        transport = f"""
    // ---- Landauer quasi-ballistic transport (CNT array) -----------------------------
    eta_s  = ALPHA*(vgs - vth_eff)/(n*vt);
    eta_d  = eta_s - vds/(n*vt);
    itube  = `P_G0*TTR*n*vt*(softplus(eta_s) - softplus(eta_d));
    ntube  = DCNT*weff*(1.0 - FMET);
    gmet   = FMET*DCNT*weff*`P_G0*TTR;             // metallic-tube ohmic shunt
    ids    = ntube*itube*(1.0 + LAMBDA*vds_abs) + gmet*vds;"""
    else:
        transport = f"""
    // ---- drift-diffusion with velocity saturation -----------------------------------
    vov    = 2.0*n*vt*softplus((vgs - vth_eff)/(2.0*n*vt));   // EKV-type smooth overdrive
    vsatv  = VSAT*L/mu_t;                                      // velocity-saturation voltage
    vdsat  = vov/(1.0 + vov/vsatv);
    beta   = mu_t*cox_eff*weff/L;
    isat   = beta*vov*vov/(2.0*(1.0 + vov/vsatv));
    ids    = isat*tanh(2.0*vds/(vdsat + 1.0e-9))*(1.0 + LAMBDA*vds_abs);"""
    return f"""// =====================================================================================
//  {name}.va  --  UCM-CFET compact model, {dev['material']} {dev['polarity']}-FET
//  Platform tag: {dev['platform_tag']}   Transport: {dev['transport']}
//  Generated by sim/gen_veriloga.py on {datetime.date.today()} from sim/platforms.py
//  Terminals: d g s b   (b is a reference terminal; tie to s in circuits)
//  Internal : di si (series resistance), tj (self-heating temperature rise, K)
//  Equations: doc/model_spec.md  -- identical to sim/ucm.py and netlists/ngspice/ucm_cfet.lib
// =====================================================================================
`include "constants.vams"
`include "disciplines.vams"
`define P_G0 (4.0*`P_Q*`P_Q/`P_H)      // Landauer conductance of one CNT (2 spins x 2 valleys)

module {name}(d, g, s, b);
inout d, g, s, b;
electrical d, g, s, b;
electrical di, si;        // internal drain / source
electrical tj;            // temperature rise node (V == K)

parameter integer TYPE = {sign} from [-1:1];   // +1 n-type, -1 p-type (fixed for this cell)
{plist}

// ---------------------------------------------------------------- local variables -----
real weff, tamb, tdev, vt, cox_eff, n, vth_t, mu_t;
real vgs, vds, vgd, vds_abs, vth_eff;
real vov, vsatv, vdsat, beta, isat, ids;
real eta_s, eta_d, itube, ntube, gmet;
real qch, qgs, qgd, rs, rd, pdiss;

analog function real softplus;      // ln(1+exp(x)) without overflow, C-infinity
    input x; real x;
    begin
        if (x > 40.0) softplus = x; else softplus = ln(1.0 + exp(x));
    end
endfunction

analog begin
    // ---- geometry & temperature ------------------------------------------------------
    if (NNS > 0) weff = NNS*2.0*(WNS + TNS); else weff = W;
    tamb    = $temperature;
    tdev    = tamb + V(tj);                              // V(tj) = 0 unless RTH > 0
    vt      = `P_K*tdev/`P_Q;
    cox_eff = COX*CQ/(COX + CQ);                        // series quantum capacitance
    n       = N0*(1.0 + `P_Q*DIT/COX);                   // trap-limited ideality
    vth_t   = VTH0 + KVTH*(tdev - TNOM);
    if (MU0 > 0.0) mu_t = MU0*pow(tdev/TNOM, -MUEXP); else mu_t = 0.0;
    rs = RSW/weff;  rd = RDW/weff;

    // ---- terminal voltages in the n-type convention ----------------------------------
    vgs = TYPE*V(g, si);
    vds = TYPE*V(di, si);
    vgd = TYPE*V(g, di);
    vds_abs = sqrt(vds*vds + 1.0e-6);
    vth_eff = vth_t - ETA*vds_abs;                       // DIBL
{transport}

    // ---- series resistances ------------------------------------------------------------
    V(d, di) <+ I(d, di)*rd;
    V(s, si) <+ I(s, si)*rs;

    // ---- channel current -----------------------------------------------------------------
    I(di, si) <+ TYPE*ids;

    // ---- charge-conserving terminal charges: Qg = Qgs + Qgd, Qs = -Qgs, Qd = -Qgd --------
    qch = 0.5*weff*L*cox_eff;
    qgs = qch*2.0*n*vt*softplus((vgs - vth_t)/(2.0*n*vt)) + CGSO*weff*vgs;
    qgd = qch*2.0*n*vt*softplus((vgd - vth_t)/(2.0*n*vt)) + CGDO*weff*vgd;
    I(g, si) <+ TYPE*ddt(qgs);
    I(g, di) <+ TYPE*ddt(qgd);

    // ---- self-heating (GaN): Tdev = Tamb + RTH*Pdiss with thermal time constant RTH*CTH --
    pdiss = ids*vds;
    if (RTH > 0.0) begin
        I(tj) <+ -pdiss;
        I(tj) <+ V(tj)/RTH;
        I(tj) <+ ddt(CTH*V(tj));
    end else begin
        V(tj) <+ 0.0;
    end
    // body terminal: reference only (no current)
    I(b, si) <+ 0.0;
end
endmodule
"""


def main():
    cal = load_calibrated()
    outdir = os.path.join(HERE, "veriloga")
    os.makedirs(outdir, exist_ok=True)
    for name, dev in DEVICES.items():
        params = dict(dev["params"]); params.update(cal.get(name, {}))
        with open(os.path.join(outdir, f"{name}.va"), "w") as f:
            f.write(module_source(name, dev, params))
        print("wrote", f"veriloga/{name}.va")


if __name__ == "__main__":
    main()
