# roN_expand.awk -- expand the ring-oscillator template for any odd N / platform
# usage: awk -v N=9 -v P=gan -f roN_expand.awk > ro9_cfet_gan.scs
BEGIN {
  dv["si"]="Lg=16n NNSn=3 NNSp=3 WNS=20n RSW=1e-4 VTHN=0.25 VTHP=0.25 MUN=0.030 MUP=0.015"
  dv["sige"]="Lg=16n NNSn=3 NNSp=3 WNS=20n RSW=1e-4 VTHN=0.25 VTHP=0.22 MUN=0.030 MUP=0.025"
  dv["tmd"]="Wn=100n Wp=200n Lg=20n VTHN=0.20 VTHP=0.25 MUN=5e-3 MUP=4e-3 RCN=5e-4 RCP=8e-4 DIT=1e16"
  dv["cnt"]="Wn=100n Wp=100n Lg=15n VTHN=0.20 VTHP=0.22 DCNT=250e6 FMET=0.01 RCN=1e-4 RCP=1e-4"
  dv["gan"]="Wn=1u Wp=4u Lg=100n VTHN=0.30 VTHP=0.50 MUN=0.15 MUP=2e-3 RTH=2e5 CTH=1e-12"
  vdd["si"]=0.7; vdd["sige"]=0.7; vdd["tmd"]=0.5; vdd["cnt"]=0.6; vdd["gan"]=1.2
  cs["si"]="0.05f"; cs["sige"]="0.05f"; cs["tmd"]="0.03f"; cs["cnt"]="0.03f"; cs["gan"]="0.1f"
  co["si"]="0.3f";  co["sige"]="0.3f";  co["tmd"]="0.3f";  co["cnt"]="0.3f";  co["gan"]="1f"
  rl["si"]=10; rl["sige"]=10; rl["tmd"]=50; rl["cnt"]=50; rl["gan"]=20
  st["si"]="5n"; st["sige"]="5n"; st["tmd"]="50n"; st["cnt"]="5n"; st["gan"]="20n"
  ms["si"]="1p"; ms["sige"]="1p"; ms["tmd"]="10p"; ms["cnt"]="1p"; ms["gan"]="5p"
  printf "// ro%d_cfet_%s.scs -- generated by roN_expand.awk\n", N, P
  print "simulator lang=spectre"; print "global 0"
  printf "include \"inv_cfet_%s.scs\"\n", P
  printf "parameters VDD=%s TEMP=27 CSTACK=%s COUT=%s RLOCAL=%s MISMATCH=0\n", vdd[P], cs[P], co[P], rl[P]
  printf "parameters %s\n", dv[P]
  # pass-through list "Lg=Lg VTHN=VTHN ..." built from the variable names
  m = split(dv[P], toks, " "); pass = ""
  for (i = 1; i <= m; i++) { split(toks[i], kv, "="); pass = pass " " kv[1] "=" kv[1] }
  pass1 = pass; sub(/ VTHN=VTHN/, " VTHN=VTHN*(1+MISMATCH)", pass1)
  print "V1 (vdd 0) vsource type=dc dc=VDD"
  for (k = 1; k <= N; k++) {
    inn = (k == 1) ? "n" N : "n" (k - 1)
    extra = (k == 1) ? pass1 : pass
    printf "I%d (%s n%d vdd 0) inv_cfet_%s CSTACK=CSTACK COUT=COUT RLOCAL=RLOCAL \\\n   %s\n", k, inn, k, P, extra
  }
  print "ic n1=0"
  print "opt1 options temp=TEMP tnom=27 reltol=1e-4 vabstol=1e-7 iabstol=1e-13 gmin=1e-15"
  printf "tran1 tran stop=%s maxstep=%s errpreset=conservative\n", st[P], ms[P]
  s = "save"; for (k = 1; k <= N; k++) s = s " n" k; print s " V1:p"
  print "saveOptions options save=selected"
}
